[package]
name = "pandastd-mini-grep"
version = "0.1.0"
edition = "2021"
description = "A command line tool to search for a string in a file"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]